import Navbar from "@/components/navbar/Navbar"
import "./globals.css"
import { Inter } from "next/font/google"
import Footer from "@/components/footer/Footer"
import styles from "../components/styleMixinComponents/RootLayout.module.scss"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "zomato",
  description: "Generated by zomato",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={inter.className}>
        <div className={styles.lgContainer}>
          <div className={styles.justifyCenter}>
            <Navbar />
            {children}
            <Footer />
          </div>
        </div>
      </body>
    </html>
  )
}
